### ISSUE TITLE
获取拼音首字母存在问题

### ISSUE THREAD

**Issue by timlee1128** [sxei/pinyinjs#5]
pinyinUnil.getFirstLetter('长城测试物业小区') -> ZCCSWYXQ
使用的pinyin_dict_firstletter.js

**Comment by chenrihong** [comment]
长 CHANG , ZHANG  多音字

**Comment by sxei** [comment]
多音字问题暂时没办法很好的处理，除非引入多音字字典文件：pinyin_dict_polyphone.js
