### ISSUE TITLE
作者大大，这几个主要的js有cdn外链吗？

### ISSUE THREAD

**Issue by jonnzer** [sxei/pinyinjs#8]
如题

**Comment by sxei** [comment]
不好意思，暂时没有哦，有木有一些免费好用的CDN推荐？

**Comment by jonnzer** [comment]
https://github.com/staticfile/static 作者大大，要不你试试这个

**Comment by sxei** [comment]
@jonnzer 已经提交了，不知道多久会审核。https://github.com/sxei/static-1

**Comment by sxei** [comment]
楼上推荐的这个CDN都已经访问不了了。
